apiVersion: v1
kind: Service
metadata:
  labels:
    name: mysql-service
  name: mysql-service
  namespace: app-synergietransport
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql
