apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: app-synergietransport
spec:
  containers:
    - name: mysql-container
      image: devinsa777/dbsynergietransport:1.0.33
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MYSQL_PASSWORD
      ports:
        - name: mysql
          containerPort: 3306
