apiVersion: v1
kind: Pod
metadata:
  name: phpmyadmin-pod
  namespace: app-synergietransport
spec:
  containers:
    - name: phpmyadmin-container
      image: phpmyadmin:5.2.0-apache
      env:
        - name: PMA_HOST
          value: mysql-service
        - name: PMA_PORT
          value: "3306"
        - name: PMA_USER
          value: root
        - name: PMA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MYSQL_ROOT_PASSWORD
      ports:
        - name: http
          containerPort: 80
